spring:
  profiles:
    active: dev

server:
  port: 9001

sa-token:
  token-name: dh-token
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false